
using System.Collections.Generic;
using System.Data.Entity;


namespace CatalcaliWebAppV2.Entities
{
    public class DataInitializer : DropCreateDatabaseIfModelChanges<DataContext>
    {
        protected override void Seed(DataContext context)
        {
            var kategoriler = new List<Category>()
            {
                new Category(){ Name = "Çiğ Süt", Description = "Çiğ Süt"},
                new Category(){ Name = "Peynirler", Description = "Peynirler ürünleri"},
                new Category(){ Name = "Yoğurtlar", Description = "Yoğurtlar ürünleri"},
                new Category(){ Name = "Yumurtalar", Description = "Yumurtalar ürünleri"},
                new Category(){ Name = "Zeytinler", Description = "Zeytinler ürünleri"},
                new Category(){ Name = "Mantı ve Börekler", Description = "Mantı ve Börekler ürünleri"},
                new Category(){ Name = "Bal ve Pekmezler", Description = "Bal ve Pekmezler ürünleri"},
                new Category(){ Name = "Diğer Ürünlerimiz", Description = "Diğer Ürünlerimiz ürünleri"}
            };

            foreach (var kategori in kategoriler)
            {
                context.Categories.Add(kategori);
            }
            context.SaveChanges();

            var urunler = new List<Product>()
            {
                //ÇİĞ SÜT ID:1
                new Product(){ Name = "1 lt Keçi Sütü",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =15 , Stock =10 , IsApproved =true , CategoryId = 1,IsHome = true,Image = "1-lt-keci-sutu206202022280no-image.png6062020202544.png",ImageDescription="plastik şişede keçi sütü"},
                new Product(){ Name = "1 lt Manda Sütü",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =15 , Stock =10 , IsApproved =true , CategoryId = 1,IsHome = true,Image = "1-lt-manda-sutu1206202016203no-image.png6062020202544.png",ImageDescription="plastik şişede manda sütü"},
                new Product(){ Name = "3 lt Holstein İnek Sütü (Yağ Oranı %3,5)",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =17 , Stock =10 , IsApproved =true , CategoryId = 1,IsHome = true,Image = "3-lt-holstein-sut4062020004350.jpg",ImageDescription="plastik şişede holstein süt"},
                new Product(){ Name = "5 lt Holstein İnek Sütü (Yağ Oranı %3,5)",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =25 , Stock =10 , IsApproved =true , CategoryId = 1,IsHome = true,Image = "5-lt-holstein-süt4062020004458.jpg",ImageDescription="plastik şişede holstein sütü"},
                //PEYNİRLER ID:2
                new Product(){ Name = "Ahmet Ural Keçi-Koyun Peyniri ~300 gr (kg 55,00 ₺)",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =16.50 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 2,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Ahmet Ural Keçi-Koyun Peyniri ~700 gr (kg 55,00 ₺)",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =38.50 , Stock =10 , IsApproved =true , CategoryId = 2,IsHome = true,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Ahmet Ural Tam Yağlı İnek Peyniri Sert Kalıp ~300gr (kg 49₺)",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =14.70 , Stock =10 , IsApproved =true , CategoryId = 2,IsHome = true,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Ahmet Ural Tam Yağlı İnek Peyniri Sert Kalıp ~700gr (kg 49₺)",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =34.30 , Stock =10 , IsApproved =true , CategoryId = 2,IsHome = true,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Ahmet Ural Tam Yağlı İnek Peyniri Yumuşak Kalıp ~300gr (kg 45₺)",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =13.50 , Stock =10 , IsApproved =true , CategoryId = 2,IsHome = true,Image = "yumusak-peynir-300-gr12062020162110.jpg"},
                //YOĞURTLAR ID:3
                new Product(){ Name = "Ahmet Ural İnek-Manda Yoğurdu 1 kg",Description="Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =10 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 3,Image = "1-kg-ahmetural-yogurt4062020004704.jpg"},
                new Product(){ Name = "Ahmet Ural İnek-Manda Yoğurdu 2 kg",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =19 , Stock =10 , IsApproved =true,IsHome=true , CategoryId = 3,Image = "1-kg-ahmetural-yogurt4062020004704.jpg"},
                new Product(){ Name = "Ahmet Ural İnek-Manda Yoğurdu 3 kg",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =26 , Stock =10 , IsApproved =true , CategoryId =3,IsHome = true,Image = "1-kg-ahmetural-yogurt4062020004704.jpg"},
                new Product(){ Name = "Ahmet Ural İnek-Manda Yoğurdu 5 kg",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =38 , Stock =10 , IsApproved =true , CategoryId = 3,IsHome = true,Image = "1-kg-ahmetural-yogurt4062020004704.jpg"},
                new Product(){ Name = "Ahmet Ural Manda Kova Yoğurt 2 kg",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =42 , Stock =10 , IsApproved =true ,IsHome = true, CategoryId = 3,Image = "1-kg-ahmetural-yogurt4062020004704.jpg"},
                new Product(){ Name = "Ahmet Ural Manda Kova Yoğurt 500 gr",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =15.50 , Stock =10 , IsApproved =true ,IsHome = true, CategoryId = 3,Image = "1-kg-ahmetural-yogurt4062020004704.jpg"},
                new Product(){ Name = "Ahmet Ural Manda Tava Yoğurt 1,5 kg",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =34 , Stock =10 , IsApproved =true ,IsHome = true, CategoryId = 3,Image = "1-kg-ahmetural-yogurt4062020004704.jpg"},
                //YUMURTALAR ID:4
                new Product(){ Name = "Gezen Tavuk Yumurtası 10 Adet", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =12 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 4,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Gezen Tavuk Yumurtası 15 Adet",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =18 , Stock =10 , IsApproved =true , CategoryId = 4,IsHome = true,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Gezen Tavuk Yumurtası 30 Adet",Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.", Price =27 , Stock =10 , IsApproved =true , CategoryId =4,IsHome = true,Image = "no-image.png6062020202544.png"},
                //ZEYTİNLER ID:5
                new Product(){ Name = "Genç Fidan Siyah Zeytin 100 gr (kg 25₺)", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =2.50 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 5,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Genç Fidan Siyah Zeytin 500 gr (kg 25₺)", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =12.50 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 5,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Siyah Zeytin İri 100 gr (kg 30₺)", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =3 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 5,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Siyah Zeytin İri 100 gr (kg 35₺)", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =3.50 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 5,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Siyah Zeytin İri 500 gr (kg 30₺)", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =15 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 5,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Siyah Zeytin İri 500 gr (kg 35₺)", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =17.50 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 5,Image = "no-image.png6062020202544.png"},
                //MANTI VE BÖREKLER ID:6
                new Product(){ Name = "Duble Kıymalı Mantı 500 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =15 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 6,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Paçanga Böreği 6’lı Paket", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =22 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 6,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Patatesli Gül Böreği 6’lı Paket", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =14 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 6,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Patatesli Sigara Böreği 25’li Paket", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =11 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 6,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Peynirli Gül Böreği 6’lı Paket", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =14 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 6,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Peynirli Sigara Böreği 25’li Paket", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =11 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 6,Image = "no-image.png6062020202544.png"},
                //BAL VE PEKMEZLER ID:7
                new Product(){ Name = "Çiçek Balı (Artvin/Yusufeli) 850 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =65 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 7,Image = "ihlamurbali6062020163158.jpg"},
                new Product(){ Name = "Ihlamur-Kestane Balı (Artvin/Yusufeli) 850 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =65 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 7,Image = "ihlamurbali6062020163158.jpg"},
                new Product(){ Name = "Kestane Balı 850 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =145 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 7,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Organik Sertifikalı Çiçek Balı 500 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =55 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 7,Image = "organik-sertifikali-camik-kekik-bali1206202016205no-image.png6062020202544.png"},
                new Product(){ Name = "Pekmez Dut 850 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =24 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 7,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Pekmez Üzüm 850 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =24 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 7,Image = "no-image.png6062020202544.png"},
                //DİĞER ID:8
                new Product(){ Name = "Çekirdek Aile Paketi", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =73 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 8,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "Çifte Kavrulmuş Tahin 950 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =37 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 8,Image = "tahin-950-gr606202016481no-image.png6062020202544.png"},
                new Product(){ Name = "Ihlamur 50 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =7.50 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 8,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "İllaki El Yapımı Meyveli Gofret 900 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =20 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 8,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "İllaki El Yapımı Vanilyalı Gofret 450 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =9 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 8,Image = "no-image.png6062020202544.png"},
                new Product(){ Name = "İllaki El Yapımı Vanilyalı Gofret 900 gr", Description = "Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Price =17 , Stock =10 , IsApproved =true ,IsHome=true, CategoryId = 8,Image = "no-image.png6062020202544.png"},
            };
            foreach (var urun in urunler)
            {
                context.Products.Add(urun);
            }

            context.SaveChanges();

            var kargo = new List<Shipping>()
            {
                new Shipping(){ShippingName="Çatalcalı Kargo", ShippingDescription="",ShippingFee= 1}
            };

            foreach (var item in kargo)
            {
                context.Shippings.Add(item);
            }
            context.SaveChanges();

            base.Seed(context);
        }

    }
}
